repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: <latest>
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: mise exec -- pyright
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/adrienverge/yamllint
    rev: <latest>
    hooks:
      - id: yamllint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: <latest>
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: <latest>
    hooks:
      - id: actionlint

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: <latest>
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
